# Generated by Django 5.2.6 on 2025-09-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('population', models.IntegerField(default=3500)),
                ('affected_pct_min', models.FloatField(default=0.25)),
                ('affected_pct_max', models.FloatField(default=0.35)),
                ('shelter_needed_min', models.IntegerField(default=800)),
                ('shelter_needed_max', models.IntegerField(default=900)),
                ('hospital_operational_pct', models.FloatField(default=0.4)),
                ('fatalities', models.IntegerField(default=80)),
                ('injured_severe_min', models.IntegerField(default=60)),
                ('injured_severe_max', models.IntegerField(default=80)),
                ('injured_mild_min', models.IntegerField(default=800)),
                ('injured_mild_max', models.IntegerField(default=900)),
            ],
        ),
    ]
