# Generated by Django 5.2.6 on 2025-09-16 01:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('status', models.CharField(choices=[('derribado', 'Derribado'), ('parcialmente', 'Parcialmente dañado'), ('ok', 'Operativo')], default='derribado', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('total_beds', models.IntegerField(default=50)),
                ('available_beds', models.IntegerField(default=20)),
                ('operational', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric', models.CharField(max_length=80)),
                ('value', models.FloatField()),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(max_length=80)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('capacity', models.IntegerField(default=100)),
                ('occupants', models.IntegerField(default=0)),
            ],
        ),
    ]
